name: Greeting
on:
  fork:
  issues:
    types: [opened]
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened]
  pull_request_review_comment:
    types: [created]

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/first-interaction@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "<h1>It's great having you contribute to this project</h1> Welcome to the KPGU Student club :nerd_face:"
          pr-message: "<h1>It's great having you contribute to this project</h1> Welcome to the KPGU Student club :nerd_face:"
          footer: 'If you would like to continue contributing to open source and would like to do it with an awesome inclusive club, you should join our <a href="https://discord.gg/dmNEPXT8vt">Discord</a> chat and our <a href="https://github.com/orgs/KPGU-Student-Club/">GitHub Organisation</a> - we help and encourage each other to contribute to open source little and often 🤓 . Any questions let us know.'
